### ISSUE TITLE
dev mode does not allow unimported etherbase

### ISSUE THREAD

**Issue by BelfordZ** [etclabscore/core-geth#187]
When running geth in dev mode, I'd like to be able to provide a public key as the etherbase, which should result in a running a private testnet with my address having a huge balance.

#### Backtrace

![image](https://user-images.githubusercontent.com/1787231/93647880-4d0cac00-f9be-11ea-96b5-1e6a6a7be374.png)

**Comment by meowsbits** [comment]
Dev mode (so far) works exclusively with Clique consensus, and thus needs a private key to sign the "mined" blocks. 

Check out https://github.com/ethereum/go-ethereum/pull/21301, where I added the ability to use an arbitrary key instead of an always-random one in `--dev` mode. TLDR is you can use an arbitrary key as long as geth can find and unlock it.

``` 
geth --dev --keystore=some/where --miner.etherbase=0x... --password=pass/file.txt
```

In fact, if the keyfile is the first OR only file in the `--keystore`, you don't need to use `--miner.etherbase`.

I've also got some iterations existing of a `--dev.ethash` mode that doesn't require unlocking the etherbase, but IMO that would be a slightly different feature request/issue.

**Comment by meowsbits** [comment]
If you're will to use a custom compiled geth, you can also hack your etherbase into the `DeveloperGenesisBlock` `Alloc` field.

**Comment by BelfordZ** [comment]
ethhash devmode would be really great! Feel free to close this issue in favour of that one!
