### ISSUE TITLE
no full syncked nodes in params/bootnodes_classic.go, Check nodes

### ISSUE THREAD

**Issue by lxgn** [etclabscore/core-geth#321]
Hi there,

In this list params/bootnodes_classic.go only one worked not syncked node.
more 30 not accessible.
enode://b9e893ea9cb4537f4fed154233005ae61b441cd0ecd980136138c304fefac194c25a16b73dac05fc66a4198d0c15dd0f33af99b411882c68a019dfa6bb703b9d@18.130.93.66:30303

I'm start sync from 0 block and my node long time wait and connect to ethereum (no classic) nodes with geth 1.9.xx

Check bootnodes list and change to normal worked with ethereum classic

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.11.21`
OS & Version: Linux
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by meowsbits** [comment]
Thanks for the report. 

These bootnodes seem to be relatively constant source of annoyance (and are slightly challenging to test and manage effectively because of peer capacities, availability rates, etc.)... which is why they're essentially deprecated in favor of the default [DNS peering](https://github.com/etclabscore/discv4-dns-lists/tree/etccore/all.classic.blockd.info) system.  

I'll look into a review of them too, and at the very least plan to add a note about their suspect utility and limitations.

**Comment by meowsbits** [comment]
Closing per merge of #324, thanks again for noting this @lxgn.
